# Generated by Django 4.2.7 on 2025-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_alter_product_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.IntegerField(default=0)),
                ('min_order_amount', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
