# Generated by Django 5.1.2 on 2025-11-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
