# Generated by Django 5.1.2 on 2025-11-30 03:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('product', 'user')},
        ),
    ]
