# Generated by Django 5.1.2 on 2025-12-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_comment_content_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
