# Generated by Django 5.1.2 on 2025-12-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cart_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('threshold', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percent', models.IntegerField(default=0, help_text='Discount percent (0 if fixed amount)')),
                ('max_amount', models.FloatField(blank=True, help_text='Maximum discount amount', null=True)),
                ('min_purchase', models.FloatField(default=0, help_text='Minimum cart subtotal to use voucher')),
                ('fixed_amount', models.FloatField(blank=True, help_text='Fixed discount amount (use instead of percent when set)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vouchers/')),
                ('free_shipping', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True)),
                ('ranks', models.ManyToManyField(blank=True, related_name='vouchers', to='store.rank')),
            ],
        ),
    ]
