# Generated by Django 5.1.2 on 2024-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_post_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='employs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
