# Generated by Django 5.1.2 on 2024-11-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_employs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employs',
            new_name='employ',
        ),
    ]
